In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [177]:
df = pd.read_csv('star_classification.csv')
df["class"].unique()
df = df[0:20000]
x = df.drop('class', axis=1)
x = x.drop("obj_ID", axis=1)
x = x.drop("spec_obj_ID", axis=1)
y = df['class']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)
###
theta = np.zeros( (15,) ) #15 attributes in the dataset
iterations = 500
alpha = 0.000002    #the learning rate
###
classes = {'GALAXY':0, 'QSO':1, 'STAR':2 }
print(y.unique())
x





['GALAXY' 'QSO' 'STAR']


alpha      delta         u         g         r         i  \
0      135.689107  32.494632  23.87882  22.27530  20.39501  19.16573   
1      144.826101  31.274185  24.77759  22.83188  22.58444  21.16812   
2      142.188790  35.582444  25.26307  22.66389  20.60976  19.34857   
3      338.741038  -0.402828  22.13682  23.77656  21.61162  20.50454   
4      345.282593  21.183866  19.43718  17.58028  16.49747  15.97711   
...           ...        ...       ...       ...       ...       ...   
19995  116.742115  42.269971  22.84368  22.29973  20.75661  19.95866   
19996  118.188167  44.085136  25.64453  22.74920  20.78390  19.89102   
19997  123.109994  58.186645  19.60161  19.41832  19.41733  19.13950   
19998  359.461825  28.348221  19.39042  17.85960  17.23222  16.95590   
19999  344.763611  14.038418  25.97670  21.18209  20.23094  19.89018   

              z  run_ID  rerun_ID  cam_col  field_ID  redshift  plate    MJD  \
0      18.79371    3606       301        2        79  0.634794   5812  56354   
1      21.61427    4518       301        5       119  0.779136  10445  58158   
2      18.94827    3606       301        2       120  0.644195   4576  55592   
3      19.25010    4192       301        3       214  0.932346   9149  58039   
4      15.54461    8102       301        3       137  0.116123   6121  56187   
...         ...     ...       ...      ...       ...       ...    ...    ...   
19995  19.47037    1402       301        4        70  0.476464   3666  55185   
19996  19.35816    1402       301        4        84  0.501545   6376  56269   
19997  19.05412    4264       301        6       155  1.854104   1873  54437   
19998  16.89005    4152       301        1       103  0.000079   2803  54368   
19999  19.65660    1739       301        3       204 -0.000178    741  52261   

       fiber_ID  
0           171  
1           427  
2           299  
3           775  
4           842  
...         ...  
19995       973  
19996       695  
19997       316  
19998       396  
19999       595  

[20000 rows x 15 columns]

In [74]:
def computeCost( X, y, theta ):
  

    m = X.shape[0]#number of training examples

    J = 0

    J = (1 / (2.0*m) ) * np.sum( ( ( np.dot(X,theta)-y)**2 ) )

    return J

In [4]:
def transformYtoNum(y):
    # Transforms String classes to integers
    y_new = np.zeros((len(y)))
    for i in range(len(y)):
        y_new[i] = classes.get(y[i])

    return y_new

In [178]:
# Converting pd frames to numpy arrays
y_train = y_train.to_numpy()
x_train = x_train.to_numpy()
y_test = y_test.to_numpy()
x_test = x_test.to_numpy()
print(type(y_train))

<class 'numpy.ndarray'>


Scaling των τιμων καθως ορισμενες ιδιοτητες του dataset περιλαμβανουν τιμες με πολλα ψηφια και οδηγουσαν σε overflow με αποτελεσμα την παραγωγη theta με τιμες NaN.

In [192]:

y_train_transformed = transformYtoNum(y_train)

# Using StandardScaler for decimal values with many digits so OVERFLOW in calculations is prevented
scaler=StandardScaler()
x_train_scaler=scaler.fit_transform(x_train)
print("Before scaler:\n", x_train)
print("After scaler:\n", x_train_scaler)

Before scaler:
 [[ 1.69683592e+02 -2.08234967e+00  2.45212200e+01 ...  3.77400000e+03
   5.52440000e+04  4.76000000e+02]
 [ 8.86939651e+00 -1.14569542e+00  2.48811000e+01 ...  7.86700000e+03
   5.70030000e+04  9.57000000e+02]
 [ 1.34287502e+02  1.09339668e+01  2.01741600e+01 ...  2.67100000e+03
   5.41410000e+04  6.30000000e+02]
 ...
 [ 1.48137883e+02  9.84109050e-01  1.79404800e+01 ...  2.67000000e+02
   5.16080000e+04  5.34000000e+02]
 [ 5.58294316e+01  9.76439658e+00  1.77922400e+01 ...  2.67900000e+03
   5.43680000e+04  2.87000000e+02]
 [ 1.89902619e+02  3.37795907e+01  2.49314200e+01 ...  3.97100000e+03
   5.53220000e+04  4.50000000e+02]]
After scaler:
 [[-0.08300705 -1.29521763  1.09045971 ... -0.43992811 -0.16558138
   0.10628772]
 [-1.69235606 -1.24618879  1.25025044 ...  0.94950427  0.80190371
   1.90063875]
 [-0.43723363 -0.6138831  -0.83968341 ... -0.81435858 -0.77225339
   0.68077849]
 ...
 [-0.29862586 -1.13470492 -1.83146224 ... -1.6304337  -2.16545392
   0.32265437]
 [-1

Παρακατω υπαρχει μια υλοποιηση του Gradient descent που κανει χρηση της computeCost(), δηλαδη της least square method.

In [145]:
def train_linear_regression(X, y):
    
    # Linear regression normal equation
    theta = np.linalg.inv(X.T @ X) @ (X.T @ y)
    return theta


def predict(X, theta):
    return X @ theta



def gradient_descent(X, y, theta, learning_rate, iterations):
    
    m = len(y)  # Number of samples
    cost_history = [] 
    print(theta.shape)
    
    for _ in range(iterations):
        #print(_)
        # Calculate predictions
        predictions = X @ theta
        
        # Compute the gradient of the cost function
        gradient = (1 / m) * X.T @ (predictions - y)
        #print(gradient)
        
        # Update theta
        theta = theta - learning_rate * gradient
        
        # Compute the cost and save it
        cost = computeCost(X, y, theta)
        cost_history.append(cost)
    
    return theta, cost_history

In [180]:


y_test_transformed = transformYtoNum(y_test)
#print(x_train.shape)
theta_array = []
for model in range(3):
    y_binary = (y_train_transformed == model).astype(int)
    theta_temp, history = gradient_descent(x_train_scaler, y_binary, theta, alpha, iterations)
    #theta_temp = train_linear_regression(x_train, y_binary)
    print(theta_temp)
    theta_array.append(theta_temp)

print(history)  




(15,)
[ 4.00867021e-06 -1.74075971e-05  1.25853836e-04  6.95232429e-05
 -2.68547094e-05 -8.61652518e-05 -1.12294853e-04 -6.93380590e-06
  0.00000000e+00 -6.15957872e-07  2.35100227e-05 -1.26944013e-04
 -5.40961293e-05 -5.65898120e-05 -5.51917268e-06]
(15,)
[ 7.13971201e-06  2.49915983e-05 -4.79531965e-05  2.70140447e-05
  9.83586167e-05  1.43409762e-04  1.57137240e-04  2.38779374e-05
  0.00000000e+00 -1.31312444e-05 -9.69526558e-06  2.98853690e-04
  1.10359186e-04  1.06088692e-04  2.69451101e-05]
(15,)
[-1.11483822e-05 -7.58400125e-06 -7.79006393e-05 -9.65372876e-05
 -7.15039074e-05 -5.72445101e-05 -4.48423877e-05 -1.69441315e-05
  0.00000000e+00  1.37472023e-05 -1.38147571e-05 -1.71909677e-04
 -5.62630568e-05 -4.94988803e-05 -2.14259374e-05]
[0.10957130353668909, 0.10957117850398136, 0.10957105347330534, 0.109570928444661, 0.10957080341804827, 0.10957067839346714, 0.10957055337091756, 0.10957042835039947, 0.10957030333191282, 0.10957017831545757, 0.10957005330103371, 0.109569928288641

Στον παρακατω κωδικα εχει χρησιμοποιηθει μια μεθοδος classification με βαση το μεσο ορο των προβλεψεων καθε ενος μοντελου (3 μοντελα, ενα για καθε κατηγορια), ωστοσο το ποσοστο του accuracy εξακολουθει να μην ειναι καλο λογω της φυσης του linear regression που δεν ειναι καταλληλο για classification tasks.

In [191]:
scores = np.array([predict(x_test, theta) for theta in theta_array]).T  # shape (n_samples, num_classes)

print(scores[0:5])
# Choose the class with the highest predicted score
predicted_classes = np.argmax(scores, axis=1)

column_means = np.mean(scores, axis=0)
print("Column means:\n", column_means)

def predict_by_mean(scores, column_means):

    predicted_classes = []
    for i in range(scores.shape[0]):

        for j in range(3):
            if scores[i][j] > column_means[j]:
                predicted_classes.append(j)
                break
    
    return predicted_classes
        
#print(predicted_classes)

predicted_classes_by_mean = predict_by_mean(scores, column_means)
print(predicted_classes_by_mean)


sum = 0
for i in range(len(y_test_transformed)):
    sum += 1 if y_test_transformed[i] == predicted_classes_by_mean[i] else 0

print("Accuracy:", sum/20000)
#print(y_binary)

[[-3.02024547  5.73487036 -2.71462488]
 [-3.8979167   7.47298931 -3.57507261]
 [-3.19342955  6.0774923  -2.88406275]
 [-3.57637964  6.81242968 -3.23605004]
 [-3.57951315  6.83039593 -3.25088278]]
Column means:
 [-3.44810462  6.58289519 -3.13479057]
[0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 2, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 2, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 